services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: academy-mamysehat-web
    container_name: academy-mamysehat-web
    restart: unless-stopped
    volumes:
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - academy-mamysehat
    ports:
      - "8005:80"

networks:
  academy-mamysehat: